### ISSUE TITLE
Refuses to open the sqlite3 dll even though it's in the same directory

### ISSUE THREAD

**Issue by HackingIntoYourHeart** [akalankauk/C-Browser-Password-Cracker#1]

**Comment by alik604** [comment]
might need 

` HMODULE sqliteLib = LoadLibrary(L".\\my dll directory\\my dll.dll");`
`HMODULE sqliteLib = LoadLibrary("C:\\Users\\user\\CLionProjects\\injection-grabber\\sqlite3.dll");`


note the ./
